name: Build

on:
  workflow_dispatch:

jobs:
  ucrt64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          release: true
          cache: true
          location: D:\
          install: mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-boost mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-clang mingw-w64-ucrt-x86_64-llvm mingw-w64-ucrt-x86_64-lld mingw-w64-ucrt-x86_64-lldb mingw-w64-ucrt-x86_64-cninja mingw-w64-ucrt-x86_64-cppcheck mingw-w64-ucrt-x86_64-gdb mingw-w64-ucrt-x86_64-iconv mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-nodejs mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-yasm mingw-w64-ucrt-x86_64-nasm mingw-w64-ucrt-x86_64-ccache mingw-w64-ucrt-x86_64-doxygen mingw-w64-ucrt-x86_64-ctags
      - name: Compress Archive
        shell: cmd
        run: |
          7z a "mingw-w64-ucrt-x86_64-gcc.zip" "D:\msys64\ucrt64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ucrt64
          path: mingw-w64-ucrt-x86_64-gcc.zip

  clang64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          release: true
          cache: true
          location: D:\
          install: mingw-w64-clang-x86_64-gcc mingw-w64-clang-x86_64-boost mingw-w64-clang-x86_64-cmake mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-llvm mingw-w64-clang-x86_64-lld mingw-w64-clang-x86_64-lldb mingw-w64-clang-x86_64-cninja mingw-w64-clang-x86_64-cppcheck mingw-w64-clang-x86_64-gdb mingw-w64-clang-x86_64-iconv mingw-w64-clang-x86_64-make mingw-w64-clang-x86_64-nodejs mingw-w64-clang-x86_64-make mingw-w64-clang-x86_64-yasm mingw-w64-clang-x86_64-nasm mingw-w64-clang-x86_64-ccache mingw-w64-clang-x86_64-doxygen mingw-w64-clang-x86_64-ctags
      - name: Compress Archive
        shell: cmd
        run: |
          mkdir D:\msys64\clang64\include\c++\v1\bits
          move stdc++.h D:\msys64\clang64\include\c++\v1\bits
          7z a "mingw-w64-clang-x86_64-gcc.zip" "D:\msys64\clang64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clang64
          path: mingw-w64-clang-x86_64-gcc.zip
