name: MSYS2

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Config Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          release: true
          cache: true
          install: mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-boost mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-clang mingw-w64-ucrt-x86_64-llvm mingw-w64-ucrt-x86_64-lld mingw-w64-ucrt-x86_64-lldb mingw-w64-ucrt-x86_64-cninja mingw-w64-ucrt-x86_64-cppcheck mingw-w64-ucrt-x86_64-gdb mingw-w64-ucrt-x86_64-iconv mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-nodejs mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-yasm mingw-w64-ucrt-x86_64-nasm mingw-w64-ucrt-x86_64-ccache mingw-w64-ucrt-x86_64-doxygen mingw-w64-ucrt-x86_64-ctags

      - name: Setup 7z
        uses: milliewalky/setup-7-zip@v1
      - name: Compress Archive
        shell: cmd
        run: |
          del /f /q *.zip
          7z a "mingw-w64-ucrt-x86_64-gcc.zip" "C:\msys64\ucrt64"

      - name: Commit and Push files
        run: |
          git add .
          git commit -m "Update Configs"
          git push
