name: MSYS2

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Config Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          location: D:\
          update: true
          install: mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-gdb

      - name: Compress Archive
        run: |
          del /f /q *.zip
          "C:/Program Files/7-Zip/7z.exe" a "mingw-w64-ucrt-x86_64-gcc.zip" "D:\msys64\ucrt64"

      - name: Commit and Push files
        run: |
          git add .
          git commit -m "Update Configs"
          git push
