name: MSYS2

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Input the name for the release.'
        required: true
        default: 'Release'
      release_tag:
        description: 'Input the tag for the release.'
        required: true
        default: 'v1.0.0'

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    steps:

      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          location: D:\meow\
          # update: true
          # install: git mingw-w64-ucrt-x86_64-gcc

      - shell: msys2 {0}
        run: echo '${{ steps.msys2.outputs.msys2-location }}'
      - shell: msys2 {0}
        run: |
          echo 'Running in MSYS2!'
          cmd
        # ./ci-build.sh

      - uses: milliewalky/setup-7-zip@v1
      - run: |
          7z a "msys2-ucrt64.zip" "D:\meow"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.event.inputs.release_tag}}
          release_name: ${{github.event.inputs.release_name}}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./msys2-ucrt64.zip
          asset_name: msys2-ucrt64.zip
          asset_content_type: application/zip