name: MSYS2

on:
  workflow_dispatch:

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          # update: true
          # install: git mingw-w64-ucrt-x86_64-gcc
      - shell: msys2 {0}
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh
          cmd
      - run: echo '${{ steps.msys2.outputs.msys2-location }}'