name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Tag name of release
        required: false

jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        
      - name: Create text file
        run: |
          echo This is the content of the file. > output.txt

      - name: Create Tag
        run: |
          setlocal
          for /f "tokens=*" %%a in ('powershell -Command "Get-Date -Format 'vyyyyMMdd_HHmm'"') do set tag_name=%%a
          if not "%{github.event.inputs.tag_name}%"=="" (
            set tag_name=%{github.event.inputs.tag_name}%
          )
          git tag %tag_name%
          git push --tags
          echo tag_name=%tag_name% >> $env:GITHUB_OUTPUT

      - name: Create Release
        run: |
          set -x
          gh release create "${{ steps.create_tag.outputs.tag_name }}" ./output.txt
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_NAME: "Release ${{ steps.create_tag.outputs.tag_name }}"
